### ISSUE TITLE
Creating a leaderboard to fetch number of tweets from twitter API

### ISSUE THREAD

**Issue by mridulnagpal** [OSDG-IIITH/hacktoberfest#105]
We need to create some sort of a leaderboard for the number of tweets per user. The specifications for the problem are as follows:
1. The list of users and there handles will be provided.
2. We need to count the number of tweets with #Hacktoberfest 
3. We need to keep it dynamic, i.e changes on each tweet the user tweets.
4. We need a simple HTML page to render all the scores in decreasing order and rank them.

**Comment by bhansa** [comment]
Have a look at this: https://analytics.twitter.com/accounts
