### ISSUE TITLE
Types of tweets and Organizing tweets

### ISSUE THREAD

**Issue by bhavabhuthi** [OSDG-IIITH/hacktoberfest#108]
We should list types of tweets for the events and plan how to tweet and re-tweet before, during and after the event.

**Comment by bhavabhuthi** [comment]
Types of tweets
1. People can post selfies before going to the event.
2. People can post their contribution status.

**Comment by bhavabhuthi** [comment]
To add 
3. Volunteers can post the status of their work or experience with the event or the idea

**Comment by bhansa** [comment]
4. Mentors can also post when they are able to guide participants contribute, like pr's etc.
